branch-defaults:
  Deployment:
    environment: Instantutor1210-env
environment-defaults:
  Instantutor1210-env:
    branch: null
    repository: null
global:
  application_name: Instantutor-1210
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
